version: '3.8'

services:
  index_bot:
    build: .
    image: anime-bot-image
    container_name: anime_index_bot
    restart: always
    env_file: .env
    environment:
      - BOT_TYPE=index
    depends_on:
      - mongodb

  file_bot:
    build: .
    image: anime-bot-image
    container_name: anime_file_bot
    restart: always
    env_file: .env
    environment:
      - BOT_TYPE=file
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: anime_mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
